--
-- Create table for storing keyword embeddings
-- Execute this SQL script directly in your PostgreSQL database
--

CREATE TABLE IF NOT EXISTS public.place_keyword_embeddings (
    id BIGSERIAL PRIMARY KEY,
    place_id BIGINT NOT NULL,
    keyword TEXT NOT NULL,
    embedding vector(1792),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT fk_place_keyword_embeddings_place
        FOREIGN KEY (place_id)
        REFERENCES public.places(id)
        ON DELETE CASCADE
);

--
-- Create indexes for performance
--

CREATE INDEX IF NOT EXISTS idx_place_keyword_embeddings_place_id
    ON public.place_keyword_embeddings(place_id);

CREATE INDEX IF NOT EXISTS idx_place_keyword_embeddings_keyword
    ON public.place_keyword_embeddings(keyword);

-- Vector similarity search index (using HNSW for fast approximate nearest neighbor search)
CREATE INDEX IF NOT EXISTS idx_place_keyword_embeddings_embedding
    ON public.place_keyword_embeddings
    USING hnsw (embedding vector_cosine_ops);

--
-- Add comment for documentation
--

COMMENT ON TABLE public.place_keyword_embeddings IS 'Stores vector embeddings for place keywords generated by Kanana embedding service';
COMMENT ON COLUMN public.place_keyword_embeddings.embedding IS 'Kanana 1792-dimensional vector embedding for Korean text';
