--
-- Create table for storing menu embeddings
-- Flyway migration script
--

CREATE TABLE IF NOT EXISTS public.place_menu_embeddings (
    id BIGSERIAL PRIMARY KEY,
    place_id BIGINT NOT NULL,
    menu_id BIGINT NOT NULL,
    menu_name TEXT NOT NULL,
    embedding vector(1792),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    CONSTRAINT fk_place_menu_embeddings_place
        FOREIGN KEY (place_id)
        REFERENCES public.places(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_place_menu_embeddings_menu
        FOREIGN KEY (menu_id)
        REFERENCES public.place_menus(id)
        ON DELETE CASCADE
);

--
-- Create indexes for performance
--

CREATE INDEX IF NOT EXISTS idx_place_menu_embeddings_place_id
    ON public.place_menu_embeddings(place_id);

CREATE INDEX IF NOT EXISTS idx_place_menu_embeddings_menu_id
    ON public.place_menu_embeddings(menu_id);

-- Vector similarity search index (using HNSW for fast approximate nearest neighbor search)
CREATE INDEX IF NOT EXISTS idx_place_menu_embeddings_embedding
    ON public.place_menu_embeddings
    USING hnsw (embedding vector_cosine_ops);

--
-- Add menu_embed_status column to places table
--

ALTER TABLE public.places
ADD COLUMN IF NOT EXISTS menu_embed_status VARCHAR(20) DEFAULT 'PENDING';

CREATE INDEX IF NOT EXISTS idx_places_menu_embed_status
    ON public.places(menu_embed_status);

--
-- Add comment for documentation
--

COMMENT ON TABLE public.place_menu_embeddings IS 'Stores vector embeddings for place menu names generated by Kanana embedding service';
COMMENT ON COLUMN public.place_menu_embeddings.embedding IS 'Kanana 1792-dimensional vector embedding for Korean menu names';
COMMENT ON COLUMN public.places.menu_embed_status IS 'Menu embedding status: PENDING, COMPLETED, FAILED';
