package com.mohe.spring.batch.location;

public enum SeoulLocation {
    SEOUL_JONGNO_CHEONGUN_HYOJA_DONG("서울특별시", "종로구", "청운효자동"),
    SEOUL_JONGNO_SAJIK_DONG("서울특별시", "종로구", "사직동"),
    SEOUL_JONGNO_SAMCHEONG_DONG("서울특별시", "종로구", "삼청동"),
    SEOUL_JONGNO_BUAM_DONG("서울특별시", "종로구", "부암동"),
    SEOUL_JONGNO_PYEONGCHANG_DONG("서울특별시", "종로구", "평창동"),
    SEOUL_JONGNO_MUAK_DONG("서울특별시", "종로구", "무악동"),
    SEOUL_JONGNO_GYEONGBOKGUNG_DONG("서울특별시", "종로구", "교남동"),
    SEOUL_JONGNO_GYEONGBOK_DONG("서울특별시", "종로구", "가회동"),
    SEOUL_JONGNO_JONGNO_1_2_3_4_DONG("서울특별시", "종로구", "종로1·2·3·4가동"),
    SEOUL_JONGNO_JONGNO_5_6_DONG("서울특별시", "종로구", "종로5·6가동"),
    SEOUL_JONGNO_GWANGHWA_DONG("서울특별시", "종로구", "광희동"),
    SEOUL_JONGNO_JANGCHUNG_DONG("서울특별시", "종로구", "창신제1동"),
    SEOUL_JONGNO_YONGSAN_DONG("서울특별시", "종로구", "숭인제2동"),

    // 중구
    SEOUL_JUNGGU_SOGONG_DONG("서울특별시", "중구", "소공동"),
    SEOUL_JUNGGU_HOEHYEON_DONG("서울특별시", "중구", "회현동"),
    SEOUL_JUNGGU_MYEONG_DONG("서울특별시", "중구", "명동"),
    SEOUL_JUNGGU_PIL_DONG("서울특별시", "중구", "필동"),
    SEOUL_JUNGGU_JANGCHUNG_DONG("서울특별시", "중구", "장충동"),
    SEOUL_JUNGGU_GWANGHUI_DONG("서울특별시", "중구", "광희동"),
    SEOUL_JUNGGU_EULJIRO_DONG("서울특별시", "중구", "을지로동"),
    SEOUL_JUNGGU_SINDANG_1_DONG("서울특별시", "중구", "신당제1동"),
    SEOUL_JUNGGU_SINDANG_2_DONG("서울특별시", "중구", "신당제2동"),
    SEOUL_JUNGGU_DONGHO_1_DONG("서울특별시", "중구", "동화동"),
    SEOUL_JUNGGU_HOEGIDONG("서울특별시", "중구", "청구동"),
    SEOUL_JUNGGU_YAKSU_DONG("서울특별시", "중구", "약수동"),

    // 용산구
    SEOUL_YONGSAN_HANNAM_DONG("서울특별시", "용산구", "한남동"),
    SEOUL_YONGSAN_ICHON_1_DONG("서울특별시", "용산구", "이촌제1동"),
    SEOUL_YONGSAN_ICHON_2_DONG("서울특별시", "용산구", "이촌제2동"),
    SEOUL_YONGSAN_HUAMDONG("서울특별시", "용산구", "후암동"),
    SEOUL_YONGSAN_YONGSAN_2GA_DONG("서울특별시", "용산구", "용산2가동"),
    SEOUL_YONGSAN_WONHYORO_2GA_DONG("서울특별시", "용산구", "원효로2가동"),
    SEOUL_YONGSAN_HANGANGRO_DONG("서울특별시", "용산구", "한강로동"),
    SEOUL_YONGSAN_NAMYEONG_DONG("서울특별시", "용산구", "남영동"),
    SEOUL_YONGSAN_SEOBINGGO_DONG("서울특별시", "용산구", "서빙고동"),
    SEOUL_YONGSAN_YONGMUN_DONG("서울특별시", "용산구", "용문동"),

    // 성동구
    SEOUL_SEONGDONG_GANGGYO_DONG("서울특별시", "성동구", "행당제1동"),
    SEOUL_SEONGDONG_GANGGYO2_DONG("서울특별시", "성동구", "행당제2동"),
    SEOUL_SEONGDONG_SAHA_DONG("서울특별시", "성동구", "응봉동"),
    SEOUL_SEONGDONG_KINGSEJONG_DONG("서울특별시", "성동구", "금호1가동"),
    SEOUL_SEONGDONG_KINGSEJONG2_DONG("서울특별시", "성동구", "금호2·3가동"),
    SEOUL_SEONGDONG_HAENGBOK_DONG("서울특별시", "성동구", "마장동"),
    SEOUL_SEONGDONG_HAENGBOK2_DONG("서울특별시", "성동구", "사근동"),
    SEOUL_SEONGDONG_GUMHO4GA_DONG("서울특별시", "성동구", "금호4가동"),
    SEOUL_SEONGDONG_OKSU_DONG("서울특별시", "성동구", "옥수동"),
    SEOUL_SEONGDONG_SONGSU1GA_DONG("서울특별시", "성동구", "성수1가제1동"),
    SEOUL_SEONGDONG_SONGSU2GA_DONG("서울특별시", "성동구", "성수1가제2동"),
    SEOUL_SEONGDONG_SONGSU3GA_DONG("서울특별시", "성동구", "성수2가제1동"),
    SEOUL_SEONGDONG_SONGSU4GA_DONG("서울특별시", "성동구", "성수2가제3동"),

    // 광진구
    SEOUL_GWANGJIN_GUNJA_DONG("서울특별시", "광진구", "군자동"),
    SEOUL_GWANGJIN_GUUI_1_DONG("서울특별시", "광진구", "구의제1동"),
    SEOUL_GWANGJIN_GUUI_2_DONG("서울특별시", "광진구", "구의제2동"),
    SEOUL_GWANGJIN_GUUI_3_DONG("서울특별시", "광진구", "구의제3동"),
    SEOUL_GWANGJIN_GWANGJANG_DONG("서울특별시", "광진구", "광장동"),
    SEOUL_GWANGJIN_NUE_DONG("서울특별시", "광진구", "자양제1동"),
    SEOUL_GWANGJIN_JAYANG_2_DONG("서울특별시", "광진구", "자양제2동"),
    SEOUL_GWANGJIN_JAYANG_3_DONG("서울특별시", "광진구", "자양제3동"),
    SEOUL_GWANGJIN_JAYANG_4_DONG("서울특별시", "광진구", "자양제4동"),
    SEOUL_GWANGJIN_JUNGDONG("서울특별시", "광진구", "중곡제1동"),
    SEOUL_GWANGJIN_JUNGDONG2("서울특별시", "광진구", "중곡제2동"),
    SEOUL_GWANGJIN_JUNGDONG3("서울특별시", "광진구", "중곡제3동"),
    SEOUL_GWANGJIN_JUNGDONG4("서울특별시", "광진구", "중곡제4동"),
    SEOUL_GWANGJIN_HWAYANG_DONG("서울특별시", "광진구", "화양동"),

    // 동대문구
    SEOUL_DONGDAEMUN_CHEONGNYANGNI_1_DONG("서울특별시", "동대문구", "청량리동"),
    SEOUL_DONGDAEMUN_HOEGI_DONG("서울특별시", "동대문구", "회기동"),
    SEOUL_DONGDAEMUN_HWI_GYEONG_1_DONG("서울특별시", "동대문구", "휘경1동"),
    SEOUL_DONGDAEMUN_HWI_GYEONG_2_DONG("서울특별시", "동대문구", "휘경2동"),
    SEOUL_DONGDAEMUN_JEONNONG_1_DONG("서울특별시", "동대문구", "전농1동"),
    SEOUL_DONGDAEMUN_JEONNONG_2_DONG("서울특별시", "동대문구", "전농2동"),
    SEOUL_DONGDAEMUN_YONGDU_DONG("서울특별시", "동대문구", "용두동"),
    SEOUL_DONGDAEMUN_YONGDAP_DONG("서울특별시", "동대문구", "답십리1동"),
    SEOUL_DONGDAEMUN_YONGDAP_2_DONG("서울특별시", "동대문구", "답십리2동"),
    SEOUL_DONGDAEMUN_JANGAN_1_DONG("서울특별시", "동대문구", "장안1동"),
    SEOUL_DONGDAEMUN_JANGAN_2_DONG("서울특별시", "동대문구", "장안2동"),

    // 중랑구
    SEOUL_JUNGNANG_MANGWOLSA_DONG("서울특별시", "중랑구", "망우본동"),
    SEOUL_JUNGNANG_MANGU_3_DONG("서울특별시", "중랑구", "망우3동"),
    SEOUL_JUNGNANG_MYEONMOG_1_DONG("서울특별시", "중랑구", "면목본동"),
    SEOUL_JUNGNANG_MYEONMOG_2_DONG("서울특별시", "중랑구", "면목2동"),
    SEOUL_JUNGNANG_MYEONMOG_3_DONG("서울특별시", "중랑구", "면목3·8동"),
    SEOUL_JUNGNANG_MYEONMOG_4_DONG("서울특별시", "중랑구", "면목4동"),
    SEOUL_JUNGNANG_MYEONMOG_5_DONG("서울특별시", "중랑구", "면목5동"),
    SEOUL_JUNGNANG_MYEONMOG_6_DONG("서울특별시", "중랑구", "면목7동"),
    SEOUL_JUNGNANG_SINNAE_1_DONG("서울특별시", "중랑구", "신내1동"),
    SEOUL_JUNGNANG_SINNAE_2_DONG("서울특별시", "중랑구", "신내2동"),
    SEOUL_JUNGNANG_SANGBONG_1_DONG("서울특별시", "중랑구", "상봉1동"),
    SEOUL_JUNGNANG_SANGBONG_2_DONG("서울특별시", "중랑구", "상봉2동"),
    SEOUL_JUNGNANG_JUNGHWA_1_DONG("서울특별시", "중랑구", "중화1동"),
    SEOUL_JUNGNANG_JUNGHWA_2_DONG("서울특별시", "중랑구", "중화2동"),

    // 성북구
    SEOUL_SEONGBUK_SEONGBUK_DONG("서울특별시", "성북구", "성북동"),
    SEOUL_SEONGBUK_SEONGDONG_DONG("서울특별시", "성북구", "삼선동"),
    SEOUL_SEONGBUK_BOSEONG_DONG("서울특별시", "성북구", "동선동"),
    SEOUL_SEONGBUK_JONGAM_DONG("서울특별시", "성북구", "돈암1동"),
    SEOUL_SEONGBUK_DONAM_2_DONG("서울특별시", "성북구", "돈암2동"),
    SEOUL_SEONGBUK_ANAM_DONG("서울특별시", "성북구", "안암동"),
    SEOUL_SEONGBUK_BOMUN_DONG("서울특별시", "성북구", "보문동"),
    SEOUL_SEONGBUK_JANGWI_1_DONG("서울특별시", "성북구", "장위1동"),
    SEOUL_SEONGBUK_JANGWI_2_DONG("서울특별시", "성북구", "장위2동"),
    SEOUL_SEONGBUK_JANGWI_3_DONG("서울특별시", "성북구", "장위3동"),
    SEOUL_SEONGBUK_GILEUM_1_DONG("서울특별시", "성북구", "길음1동"),
    SEOUL_SEONGBUK_GILEUM_2_DONG("서울특별시", "성북구", "길음2동"),
    SEOUL_SEONGBUK_SEOKGWAN_DONG("서울특별시", "성북구", "석관동"),

    // 강북구
    SEOUL_GANGBUK_MIA_DONG("서울특별시", "강북구", "미아동"),
    SEOUL_GANGBUK_BUN_1_DONG("서울특별시", "강북구", "번1동"),
    SEOUL_GANGBUK_BUN_2_DONG("서울특별시", "강북구", "번2동"),
    SEOUL_GANGBUK_BUN_3_DONG("서울특별시", "강북구", "번3동"),
    SEOUL_GANGBUK_SAMYANG_DONG("서울특별시", "강북구", "삼양동"),
    SEOUL_GANGBUK_SAMGAKSAN_DONG("서울특별시", "강북구", "삼각산동"),
    SEOUL_GANGBUK_SONGJUNG_DONG("서울특별시", "강북구", "송중동"),
    SEOUL_GANGBUK_SONGCHEON_DONG("서울특별시", "강북구", "송천동"),
    SEOUL_GANGBUK_SUYU_1_DONG("서울특별시", "강북구", "수유1동"),
    SEOUL_GANGBUK_SUYU_2_DONG("서울특별시", "강북구", "수유2동"),
    SEOUL_GANGBUK_SUYU_3_DONG("서울특별시", "강북구", "수유3동"),
    SEOUL_GANGBUK_UI_DONG("서울특별시", "강북구", "우이동"),
    SEOUL_GANGBUK_INSUDONG("서울특별시", "강북구", "인수동"),

    // 도봉구
    SEOUL_DOBONG_CHANG_1_DONG("서울특별시", "도봉구", "창1동"),
    SEOUL_DOBONG_CHANG_2_DONG("서울특별시", "도봉구", "창2동"),
    SEOUL_DOBONG_CHANG_3_DONG("서울특별시", "도봉구", "창3동"),
    SEOUL_DOBONG_CHANG_4_DONG("서울특별시", "도봉구", "창4동"),
    SEOUL_DOBONG_CHANG_5_DONG("서울특별시", "도봉구", "창5동"),
    SEOUL_DOBONG_DOBONG_1_DONG("서울특별시", "도봉구", "도봉1동"),
    SEOUL_DOBONG_DOBONG_2_DONG("서울특별시", "도봉구", "도봉2동"),

    // 노원구
    SEOUL_NOWON_WOLGYE_1_DONG("서울특별시", "노원구", "월계1동"),
    SEOUL_NOWON_WOLGYE_2_DONG("서울특별시", "노원구", "월계2동"),
    SEOUL_NOWON_WOLGYE_3_DONG("서울특별시", "노원구", "월계3동"),
    SEOUL_NOWON_GONGNEUNG_1_DONG("서울특별시", "노원구", "공릉1동"),
    SEOUL_NOWON_GONGNEUNG_2_DONG("서울특별시", "노원구", "공릉2동"),
    SEOUL_NOWON_HAGYE_1_DONG("서울특별시", "노원구", "하계1동"),
    SEOUL_NOWON_HAGYE_2_DONG("서울특별시", "노원구", "하계2동"),
    SEOUL_NOWON_JUNGYE_1_DONG("서울특별시", "노원구", "중계1동"),
    SEOUL_NOWON_JUNGYE_2_DONG("서울특별시", "노원구", "중계2·3동"),
    SEOUL_NOWON_JUNGYE_4_DONG("서울특별시", "노원구", "중계4동"),
    SEOUL_NOWON_SANGYE_1_DONG("서울특별시", "노원구", "상계1동"),
    SEOUL_NOWON_SANGYE_2_DONG("서울특별시", "노원구", "상계2동"),
    SEOUL_NOWON_SANGYE_3_DONG("서울특별시", "노원구", "상계3·4동"),
    SEOUL_NOWON_SANGYE_5_DONG("서울특별시", "노원구", "상계5동"),
    SEOUL_NOWON_SANGYE_6_7_DONG("서울특별시", "노원구", "상계6·7동"),
    SEOUL_NOWON_SANGYE_8_DONG("서울특별시", "노원구", "상계8동"),
    SEOUL_NOWON_SANGYE_9_DONG("서울특별시", "노원구", "상계9동"),
    SEOUL_NOWON_SANGYE_10_DONG("서울특별시", "노원구", "상계10동"),

    // 은평구
    SEOUL_EUNPYEONG_GALHYEON_DONG("서울특별시", "은평구", "갈현1동"),
    SEOUL_EUNPYEONG_GALHYEON_2_DONG("서울특별시", "은평구", "갈현2동"),
    SEOUL_EUNPYEONG_GUSO_DONG("서울특별시", "은평구", "구산동"),
    SEOUL_EUNPYEONG_DAEGOK_DONG("서울특별시", "은평구", "대조동"),
    SEOUL_EUNPYEONG_BULGWANG_1_DONG("서울특별시", "은평구", "불광1동"),
    SEOUL_EUNPYEONG_BULGWANG_2_DONG("서울특별시", "은평구", "불광2동"),
    SEOUL_EUNPYEONG_EUNGAM_1_DONG("서울특별시", "은평구", "응암1동"),
    SEOUL_EUNPYEONG_EUNGAM_2_DONG("서울특별시", "은평구", "응암2동"),
    SEOUL_EUNPYEONG_EUNGAM_3_DONG("서울특별시", "은평구", "응암3동"),
    SEOUL_EUNPYEONG_SINJEONG_DONG("서울특별시", "은평구", "신사1동"),
    SEOUL_EUNPYEONG_SINJEONG_2_DONG("서울특별시", "은평구", "신사2동"),
    SEOUL_EUNPYEONG_JINGWAN_DONG("서울특별시", "은평구", "진관동"),

    // 서대문구
    SEOUL_SEODAEMUN_HONGJE_1_DONG("서울특별시", "서대문구", "홍제1동"),
    SEOUL_SEODAEMUN_HONGJE_2_DONG("서울특별시", "서대문구", "홍제2동"),
    SEOUL_SEODAEMUN_HONGJE_3_DONG("서울특별시", "서대문구", "홍제3동"),
    SEOUL_SEODAEMUN_YEONHUI_DONG("서울특별시", "서대문구", "연희동"),
    SEOUL_SEODAEMUN_CHUNGDONG("서울특별시", "서대문구", "천연동"),
    SEOUL_SEODAEMUN_CHANGCHEON_DONG("서울특별시", "서대문구", "창천동"),
    SEOUL_SEODAEMUN_HONGJEYEOK_DONG("서울특별시", "서대문구", "북아현동"),
    SEOUL_SEODAEMUN_HYEJON_DONG("서울특별시", "서대문구", "충현동"),
    SEOUL_SEODAEMUN_HAPDONG_DONG("서울특별시", "서대문구", "홍은1동"),
    SEOUL_SEODAEMUN_HAPDONG_2_DONG("서울특별시", "서대문구", "홍은2동"),
    SEOUL_SEODAEMUN_NAMGYO_DONG("서울특별시", "서대문구", "남가좌1동"),
    SEOUL_SEODAEMUN_NAMGYO_2_DONG("서울특별시", "서대문구", "남가좌2동"),
    SEOUL_SEODAEMUN_BUK_GYO_DONG("서울특별시", "서대문구", "북가좌1동"),
    SEOUL_SEODAEMUN_BUK_GYO_2_DONG("서울특별시", "서대문구", "북가좌2동"),

    // 마포구
    SEOUL_MAPO_AHYEON_DONG("서울특별시", "마포구", "아현동"),
    SEOUL_MAPO_DAEHYEON_DONG("서울특별시", "마포구", "대흥동"),
    SEOUL_MAPO_DONGGYODONG("서울특별시", "마포구", "도화동"),
    SEOUL_MAPO_SANGSU_DONG("서울특별시", "마포구", "상암동"),
    SEOUL_MAPO_HAPJEONG_DONG("서울특별시", "마포구", "합정동"),
    SEOUL_MAPO_SEOGYO_DONG("서울특별시", "마포구", "서교동"),
    SEOUL_MAPO_YEONNAM_DONG("서울특별시", "마포구", "연남동"),
    SEOUL_MAPO_SINSEO_DONG("서울특별시", "마포구", "신수동"),
    SEOUL_MAPO_SANGAM_DONG("서울특별시", "마포구", "상암동"),
    SEOUL_MAPO_SEOKYO_DONG("서울특별시", "마포구", "성산1동"),
    SEOUL_MAPO_SEOKYO_2_DONG("서울특별시", "마포구", "성산2동"),

    // 양천구
    SEOUL_YANGCHEON_MOK_1_DONG("서울특별시", "양천구", "목1동"),
    SEOUL_YANGCHEON_MOK_2_DONG("서울특별시", "양천구", "목2동"),
    SEOUL_YANGCHEON_MOK_3_DONG("서울특별시", "양천구", "목3동"),
    SEOUL_YANGCHEON_MOK_4_DONG("서울특별시", "양천구", "목4동"),
    SEOUL_YANGCHEON_MOK_5_DONG("서울특별시", "양천구", "목5동"),
    SEOUL_YANGCHEON_SINJEONG_1_DONG("서울특별시", "양천구", "신정1동"),
    SEOUL_YANGCHEON_SINJEONG_2_DONG("서울특별시", "양천구", "신정2동"),
    SEOUL_YANGCHEON_SINJEONG_3_DONG("서울특별시", "양천구", "신정3동"),
    SEOUL_YANGCHEON_SINJEONG_4_DONG("서울특별시", "양천구", "신정4동"),
    SEOUL_YANGCHEON_SINJEONG_5_DONG("서울특별시", "양천구", "신정5동"),
    SEOUL_YANGCHEON_SINJEONG_6_DONG("서울특별시", "양천구", "신정6동"),
    SEOUL_YANGCHEON_SINJEONG_7_DONG("서울특별시", "양천구", "신정7동"),

    // 강서구
    SEOUL_GANGSEO_GAYANG_1_DONG("서울특별시", "강서구", "가양1동"),
    SEOUL_GANGSEO_GAYANG_2_DONG("서울특별시", "강서구", "가양2동"),
    SEOUL_GANGSEO_GAYANG_3_DONG("서울특별시", "강서구", "가양3동"),
    SEOUL_GANGSEO_GONGHANG_DONG("서울특별시", "강서구", "공항동"),
    SEOUL_GANGSEO_DEUNGCHON_1_DONG("서울특별시", "강서구", "등촌1동"),
    SEOUL_GANGSEO_DEUNGCHON_2_DONG("서울특별시", "강서구", "등촌2동"),
    SEOUL_GANGSEO_DEUNGCHON_3_DONG("서울특별시", "강서구", "등촌3동"),
    SEOUL_GANGSEO_BAL_SAN_1_DONG("서울특별시", "강서구", "발산1동"),
    SEOUL_GANGSEO_BANGHWA_1_DONG("서울특별시", "강서구", "방화1동"),
    SEOUL_GANGSEO_BANGHWA_2_DONG("서울특별시", "강서구", "방화2동"),
    SEOUL_GANGSEO_BANGHWA_3_DONG("서울특별시", "강서구", "방화3동"),
    SEOUL_GANGSEO_HWAGOK_1_DONG("서울특별시", "강서구", "화곡1동"),
    SEOUL_GANGSEO_HWAGOK_2_DONG("서울특별시", "강서구", "화곡2동"),
    SEOUL_GANGSEO_HWAGOK_3_DONG("서울특별시", "강서구", "화곡3동"),
    SEOUL_GANGSEO_HWAGOK_4_DONG("서울특별시", "강서구", "화곡4동"),
    SEOUL_GANGSEO_HWAGOK_6_DONG("서울특별시", "강서구", "화곡6동"),
    SEOUL_GANGSEO_HWAGOK_8_DONG("서울특별시", "강서구", "화곡8동"),
    SEOUL_GANGSEO_UJEONG_DONG("서울특별시", "강서구", "우장산동"),

    // 구로구
    SEOUL_GURO_GASAN_DONG("서울특별시", "구로구", "가리봉동"),
    SEOUL_GURO_GURO_1_DONG("서울특별시", "구로구", "구로1동"),
    SEOUL_GURO_GURO_2_DONG("서울특별시", "구로구", "구로2동"),
    SEOUL_GURO_GURO_3_DONG("서울특별시", "구로구", "구로3동"),
    SEOUL_GURO_GURO_4_DONG("서울특별시", "구로구", "구로4동"),
    SEOUL_GURO_GURO_5_DONG("서울특별시", "구로구", "구로5동"),
    SEOUL_GURO_GOCHON_1_DONG("서울특별시", "구로구", "고척1동"),
    SEOUL_GURO_GOCHON_2_DONG("서울특별시", "구로구", "고척2동"),
    SEOUL_GURO_GYE_DONG("서울특별시", "구로구", "개봉1동"),
    SEOUL_GURO_GYE_2_DONG("서울특별시", "구로구", "개봉2동"),
    SEOUL_GURO_GYE_3_DONG("서울특별시", "구로구", "개봉3동"),
    SEOUL_GURO_ONSU_DONG("서울특별시", "구로구", "오류1동"),
    SEOUL_GURO_ONSU_2_DONG("서울특별시", "구로구", "오류2동"),
    SEOUL_GURO_HANGDONG_1_DONG("서울특별시", "구로구", "항동"),

    // 금천구
    SEOUL_GEUMCHEON_GASAN_DONG("서울특별시", "금천구", "가산동"),
    SEOUL_GEUMCHEON_DOKSAN_1_DONG("서울특별시", "금천구", "독산1동"),
    SEOUL_GEUMCHEON_DOKSAN_2_DONG("서울특별시", "금천구", "독산2동"),
    SEOUL_GEUMCHEON_DOKSAN_3_DONG("서울특별시", "금천구", "독산3동"),
    SEOUL_GEUMCHEON_DOKSAN_4_DONG("서울특별시", "금천구", "독산4동"),
    SEOUL_GEUMCHEON_SIHUNG_1_DONG("서울특별시", "금천구", "시흥1동"),
    SEOUL_GEUMCHEON_SIHUNG_2_DONG("서울특별시", "금천구", "시흥2동"),
    SEOUL_GEUMCHEON_SIHUNG_3_DONG("서울특별시", "금천구", "시흥3동"),
    SEOUL_GEUMCHEON_SIHUNG_4_DONG("서울특별시", "금천구", "시흥4동"),
    SEOUL_GEUMCHEON_SIHUNG_5_DONG("서울특별시", "금천구", "시흥5동"),

    // 영등포구
    SEOUL_YEONGDEUNGPO_YEONGDEUNGPO_1_DONG("서울특별시", "영등포구", "영등포본동"),
    SEOUL_YEONGDEUNGPO_YEONGDEUNGPO_2_DONG("서울특별시", "영등포구", "영등포동"),
    SEOUL_YEONGDEUNGPO_DANGSAN_1_DONG("서울특별시", "영등포구", "당산1동"),
    SEOUL_YEONGDEUNGPO_DANGSAN_2_DONG("서울특별시", "영등포구", "당산2동"),
    SEOUL_YEONGDEUNGPO_YEUIDO_DONG("서울특별시", "영등포구", "여의동"),
    SEOUL_YEONGDEUNGPO_MUNRAE_DONG("서울특별시", "영등포구", "문래동"),
    SEOUL_YEONGDEUNGPO_SIN_GIL_1_DONG("서울특별시", "영등포구", "신길1동"),
    SEOUL_YEONGDEUNGPO_SIN_GIL_2_DONG("서울특별시", "영등포구", "신길2동"),
    SEOUL_YEONGDEUNGPO_SIN_GIL_3_DONG("서울특별시", "영등포구", "신길3동"),
    SEOUL_YEONGDEUNGPO_SIN_GIL_4_DONG("서울특별시", "영등포구", "신길4동"),
    SEOUL_YEONGDEUNGPO_SIN_GIL_5_DONG("서울특별시", "영등포구", "신길5동"),
    SEOUL_YEONGDEUNGPO_SIN_GIL_6_DONG("서울특별시", "영등포구", "신길6동"),
    SEOUL_YEONGDEUNGPO_SIN_GIL_7_DONG("서울특별시", "영등포구", "신길7동"),

    // 동작구
    SEOUL_DONGJAK_SANGDO_1_DONG("서울특별시", "동작구", "상도1동"),
    SEOUL_DONGJAK_SANGDO_2_DONG("서울특별시", "동작구", "상도2동"),
    SEOUL_DONGJAK_SANGDO_3_DONG("서울특별시", "동작구", "상도3동"),
    SEOUL_DONGJAK_SANGDO_4_DONG("서울특별시", "동작구", "상도4동"),
    SEOUL_DONGJAK_HEUKSEOK_DONG("서울특별시", "동작구", "흑석동"),
    SEOUL_DONGJAK_NORYANGJIN_1_DONG("서울특별시", "동작구", "노량진1동"),
    SEOUL_DONGJAK_NORYANGJIN_2_DONG("서울특별시", "동작구", "노량진2동"),
    SEOUL_DONGJAK_SADANG_1_DONG("서울특별시", "동작구", "사당1동"),
    SEOUL_DONGJAK_SADANG_2_DONG("서울특별시", "동작구", "사당2동"),
    SEOUL_DONGJAK_SADANG_3_DONG("서울특별시", "동작구", "사당3동"),
    SEOUL_DONGJAK_SADANG_4_DONG("서울특별시", "동작구", "사당4동"),
    SEOUL_DONGJAK_SADANG_5_DONG("서울특별시", "동작구", "사당5동"),

    SEOUL_GWANAK_BONGCHEON_1_DONG("서울특별시", "관악구", "봉천1동"),
    SEOUL_GWANAK_BONGCHEON_2_DONG("서울특별시", "관악구", "봉천2동"),
    SEOUL_GWANAK_BONGCHEON_3_DONG("서울특별시", "관악구", "봉천3동"),
    SEOUL_GWANAK_BONGCHEON_4_DONG("서울특별시", "관악구", "봉천4동"),
    SEOUL_GWANAK_BONGCHEON_5_DONG("서울특별시", "관악구", "봉천5동"),
    SEOUL_GWANAK_BONGCHEON_6_DONG("서울특별시", "관악구", "봉천6동"),
    SEOUL_GWANAK_BONGCHEON_7_DONG("서울특별시", "관악구", "봉천7동"),
    SEOUL_GWANAK_BONGCHEON_8_DONG("서울특별시", "관악구", "봉천8동"),
    SEOUL_GWANAK_BONGCHEON_9_DONG("서울특별시", "관악구", "봉천9동"),
    SEOUL_GWANAK_BONGCHEON_10_DONG("서울특별시", "관악구", "봉천10동"),
    SEOUL_GWANAK_SINRIM_1_DONG("서울특별시", "관악구", "신림동"),
    SEOUL_GWANAK_SINRIM_2_DONG("서울특별시", "관악구", "신림2동"),
    SEOUL_GWANAK_SINRIM_3_DONG("서울특별시", "관악구", "신림3동"),
    SEOUL_GWANAK_SINRIM_4_DONG("서울특별시", "관악구", "신림4동"),
    SEOUL_GWANAK_SINRIM_5_DONG("서울특별시", "관악구", "신림5동"),
    SEOUL_GWANAK_SINRIM_6_DONG("서울특별시", "관악구", "신림6동"),
    SEOUL_GWANAK_SINRIM_7_DONG("서울특별시", "관악구", "신림7동"),
    SEOUL_GWANAK_SINRIM_8_DONG("서울특별시", "관악구", "신림8동"),
    SEOUL_GWANAK_SINRIM_9_DONG("서울특별시", "관악구", "신림9동"),
    SEOUL_GWANAK_SINRIM_10_DONG("서울특별시", "관악구", "신림10동"),
    SEOUL_GWANAK_SINRIM_11_DONG("서울특별시", "관악구", "신림11동"),
    SEOUL_GWANAK_SINRIM_12_DONG("서울특별시", "관악구", "신림12동"),
    SEOUL_GWANAK_SINRIM_13_DONG("서울특별시", "관악구", "신림13동"),

    // 서초구
    SEOUL_SEOCHO_BANGBAE_1_DONG("서울특별시", "서초구", "방배1동"),
    SEOUL_SEOCHO_BANGBAE_2_DONG("서울특별시", "서초구", "방배2동"),
    SEOUL_SEOCHO_BANGBAE_3_DONG("서울특별시", "서초구", "방배3동"),
    SEOUL_SEOCHO_BANGBAE_4_DONG("서울특별시", "서초구", "방배4동"),
    SEOUL_SEOCHO_BANGBAE_BON_DONG("서울특별시", "서초구", "방배본동"),
    SEOUL_SEOCHO_SEOCHO_1_DONG("서울특별시", "서초구", "서초1동"),
    SEOUL_SEOCHO_SEOCHO_2_DONG("서울특별시", "서초구", "서초2동"),
    SEOUL_SEOCHO_SEOCHO_3_DONG("서울특별시", "서초구", "서초3동"),
    SEOUL_SEOCHO_SEOCHO_4_DONG("서울특별시", "서초구", "서초4동"),
    SEOUL_SEOCHO_YANGJAE_1_DONG("서울특별시", "서초구", "양재1동"),
    SEOUL_SEOCHO_YANGJAE_2_DONG("서울특별시", "서초구", "양재2동"),
    SEOUL_SEOCHO_UMYEON_DONG("서울특별시", "서초구", "내곡동"),
    SEOUL_SEOCHO_BANPO_1_DONG("서울특별시", "서초구", "반포1동"),
    SEOUL_SEOCHO_BANPO_2_DONG("서울특별시", "서초구", "반포2동"),
    SEOUL_SEOCHO_BANPO_3_DONG("서울특별시", "서초구", "반포3동"),
    SEOUL_SEOCHO_BANPO_4_DONG("서울특별시", "서초구", "반포4동"),
    SEOUL_SEOCHO_JAMWON_DONG("서울특별시", "서초구", "잠원동"),

    // 강남구
    SEOUL_GANGNAM_APGUJEONG_DONG("서울특별시", "강남구", "압구정동"),
    SEOUL_GANGNAM_CHEONGDAM_DONG("서울특별시", "강남구", "청담동"),
    SEOUL_GANGNAM_SAMSUNG_1_DONG("서울특별시", "강남구", "삼성1동"),
    SEOUL_GANGNAM_SAMSUNG_2_DONG("서울특별시", "강남구", "삼성2동"),
    SEOUL_GANGNAM_DAECHI_1_DONG("서울특별시", "강남구", "대치1동"),
    SEOUL_GANGNAM_DAECHI_2_DONG("서울특별시", "강남구", "대치2동"),
    SEOUL_GANGNAM_DAECHI_4_DONG("서울특별시", "강남구", "대치4동"),
    SEOUL_GANGNAM_DOGOK_1_DONG("서울특별시", "강남구", "도곡1동"),
    SEOUL_GANGNAM_DOGOK_2_DONG("서울특별시", "강남구", "도곡2동"),
    SEOUL_GANGNAM_YEOKSAM_1_DONG("서울특별시", "강남구", "역삼1동"),
    SEOUL_GANGNAM_YEOKSAM_2_DONG("서울특별시", "강남구", "역삼2동"),
    SEOUL_GANGNAM_NONHYEON_1_DONG("서울특별시", "강남구", "논현1동"),
    SEOUL_GANGNAM_NONHYEON_2_DONG("서울특별시", "강남구", "논현2동"),
    SEOUL_GANGNAM_SINSA_DONG("서울특별시", "강남구", "신사동"),
    SEOUL_GANGNAM_SEOCHO_DONG("서울특별시", "강남구", "세곡동"),
    SEOUL_GANGNAM_SUSEO_DONG("서울특별시", "강남구", "수서동"),
    SEOUL_GANGNAM_ILWON_1_DONG("서울특별시", "강남구", "일원1동"),
    SEOUL_GANGNAM_ILWON_2_DONG("서울특별시", "강남구", "일원2동"),
    SEOUL_GANGNAM_ILWON_BON_DONG("서울특별시", "강남구", "일원본동"),

    // 송파구
    SEOUL_SONGPA_JAMSIL_1_DONG("서울특별시", "송파구", "잠실본동"),
    SEOUL_SONGPA_JAMSIL_2_DONG("서울특별시", "송파구", "잠실2동"),
    SEOUL_SONGPA_JAMSIL_3_DONG("서울특별시", "송파구", "잠실3동"),
    SEOUL_SONGPA_JAMSIL_4_DONG("서울특별시", "송파구", "잠실4동"),
    SEOUL_SONGPA_JAMSIL_6_DONG("서울특별시", "송파구", "잠실6동"),
    SEOUL_SONGPA_JAMSIL_7_DONG("서울특별시", "송파구", "잠실7동"),
    SEOUL_SONGPA_SINCHON_DONG("서울특별시", "송파구", "신천동"),
    SEOUL_SONGPA_BANGI_1_DONG("서울특별시", "송파구", "방이1동"),
    SEOUL_SONGPA_BANGI_2_DONG("서울특별시", "송파구", "방이2동"),
    SEOUL_SONGPA_GARAK_1_DONG("서울특별시", "송파구", "가락1동"),
    SEOUL_SONGPA_GARAK_2_DONG("서울특별시", "송파구", "가락2동"),
    SEOUL_SONGPA_GARAK_BON_DONG("서울특별시", "송파구", "가락본동"),
    SEOUL_SONGPA_MUNJEONG_1_DONG("서울특별시", "송파구", "문정1동"),
    SEOUL_SONGPA_MUNJEONG_2_DONG("서울특별시", "송파구", "문정2동"),
    SEOUL_SONGPA_JANGJI_DONG("서울특별시", "송파구", "장지동"),
    SEOUL_SONGPA_WIRYE_DONG("서울특별시", "송파구", "위례동"),

    // 강동구
    SEOUL_GANGDONG_GANGIL_DONG("서울특별시", "강동구", "강일동"),
    SEOUL_GANGDONG_GODEOK_1_DONG("서울특별시", "강동구", "고덕1동"),
    SEOUL_GANGDONG_GODEOK_2_DONG("서울특별시", "강동구", "고덕2동"),
    SEOUL_GANGDONG_GIL_DONG("서울특별시", "강동구", "길동"),
    SEOUL_GANGDONG_DUNCHON_1_DONG("서울특별시", "강동구", "둔촌1동"),
    SEOUL_GANGDONG_DUNCHON_2_DONG("서울특별시", "강동구", "둔촌2동"),
    SEOUL_GANGDONG_MYEONGIL_1_DONG("서울특별시", "강동구", "명일1동"),
    SEOUL_GANGDONG_MYEONGIL_2_DONG("서울특별시", "강동구", "명일2동"),
    SEOUL_GANGDONG_SANGIL_DONG("서울특별시", "강동구", "상일동"),
    SEOUL_GANGDONG_SEONGNAE_1_DONG("서울특별시", "강동구", "성내1동"),
    SEOUL_GANGDONG_SEONGNAE_2_DONG("서울특별시", "강동구", "성내2동"),
    SEOUL_GANGDONG_SEONGNAE_3_DONG("서울특별시", "강동구", "성내3동"),
    SEOUL_GANGDONG_AMSA_1_DONG("서울특별시", "강동구", "암사1동"),
    SEOUL_GANGDONG_AMSA_2_DONG("서울특별시", "강동구", "암사2동"),
    SEOUL_GANGDONG_AMSA_3_DONG("서울특별시", "강동구", "암사3동"),
    SEOUL_GANGDONG_CHEONHO_1_DONG("서울특별시", "강동구", "천호1동"),
    SEOUL_GANGDONG_CHEONHO_2_DONG("서울특별시", "강동구", "천호2동"),
    SEOUL_GANGDONG_CHEONHO_3_DONG("서울특별시", "강동구", "천호3동");

    private final String city;
    private final String district;
    private final String dong;

    SeoulLocation(String city, String district, String dong) {
        this.city = city;
        this.district = district;
        this.dong = dong;
    }

    public String getCity() {
        return city;
    }

    public String getDistrict() {
        return district;
    }

    public String getDong() {
        return dong;
    }

    public String getFullName() {
        return city + " " + district + " " + dong;
    }
}
